In [1]:
import numpy as np

- агрегирование

Агрегирование - вычисление неких сводных показателей.

In [2]:
arr_1 = np.random.random(10)
arr_1

array([0.81592491, 0.86150489, 0.64945838, 0.37494713, 0.98926085,
       0.94111132, 0.32647303, 0.15962088, 0.26094086, 0.76058844])

In [3]:
# сумма
# 1d-array
np.sum(arr_1)

6.139830698473746

In [4]:
# 2d-array
np.sum(arr_1.reshape((2,5)))

6.139830698473746

In [19]:
np.sum(arr_1.reshape((2,5)), axis=0)

array([1.75703624, 1.18797792, 0.80907926, 0.63588799, 1.74984929])

In [5]:
# минимум
np.min(arr_1)

0.15962087835489602

In [6]:
# максимум
np.max(arr_1)

0.9892608490794068

In [7]:
# среднее арифметическое
np.mean(arr_1)

0.6139830698473746

- сравнения

In [8]:
arr_2 = np.arange(7)
arr_2

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
arr_2 != 2

array([ True,  True, False,  True,  True,  True,  True])

In [10]:
arr_2 == 2

array([False, False,  True, False, False, False, False])

In [11]:
arr_2 > 3

array([False, False, False, False,  True,  True,  True])

In [12]:
np.arange(10).reshape((5,2)) >= 4

array([[False, False],
       [False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [13]:
# общее сравнение
# имеются ли в массиве значения, отвечающие условию
condition = arr_2 > 4
np.any(condition)

True

In [14]:
# все ли значения отвечают условию
np.all(arr_2 < 2)

False

In [15]:
arr_3 = np.arange(10).reshape((5,2))
arr_3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
np.any(arr_3 > 7, axis=0)

array([ True,  True])

In [17]:
np.any(arr_3 > 7, axis=1)

array([False, False, False, False,  True])

In [18]:
np.all(arr_3 < 5, axis=0)

array([False, False])

- маскирование

In [20]:
arr_4 = np.random.randint(10, size=5)
arr_4

array([6, 8, 8, 5, 5])

In [21]:
# маска - массив с булевыми значениями
c = arr_4 < 6
c

array([False, False, False,  True,  True])

In [22]:
arr_4[c]

array([5, 5])

In [30]:
# Побитовые операторы & = and, | = or
arr_4[(arr_4 > 5) & (arr_4 < 8)]

array([6])

In [31]:
arr_4[arr_4 != 8]

array([6, 5, 5])

- прихотливая индексация (fancy indieces)

In [32]:
arr_5 = np.arange(10, 20)
arr_5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
# с помощью списка индексов
arr_5[[3,0,5,7]]

array([13, 10, 15, 17])

In [37]:
# с помощью массива индексов
arr_5[np.array([3,0,5,7])]

array([13, 10, 15, 17])

In [38]:
# с помощью прихотливой индексации можно менять форму результирующего массива
fi = np.array(
    [[3,0,1],
     [1,1,5]]
)
arr_5[fi]

array([[13, 10, 11],
       [11, 11, 15]])